# Projek Akhir Pemrosesan Teks

Kelompok 4 :
1. Bima Setia Sugiharto (24031554040)
2. Muhammad Geralldo Agatha Saputra (24031554091)
3. Moh. Rasya Al Khalifi (24031554132)

## Import Data

In [86]:
import pandas as pd
import re
import nltk
nltk.download("punkt")
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER040824\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [87]:
df = pd.read_csv("livechatyt.csv")
df.head()

,timestamp,username,message
0,2025-11-02 14:56:26,@markxushi,HALO MPL
1,2025-11-02 14:56:27,@IRVAN_24,gak sesuai jadwal
2,2025-11-02 14:56:27,@ZyyyElMahir,IT'S ONIC TIME
3,2025-11-02 14:56:31,@Sandi-or4rd,1556
4,2025-11-02 14:56:32,@am_I02,jam 17:00 paling lambat jam 7:00 malaem haha

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  10000 non-null  object
 1   username   10000 non-null  object
 2   message    9999 non-null   object
dtypes: object(3)
memory usage: 234.5+ KB

## Data Pre-Processing

In [89]:
df['message'] = df['message'].astype(str).str.lower()
df["message"] = df["message"].replace("false", pd.NA)
df = df.dropna(subset=["message"])

In [90]:
df = df.drop_duplicates(subset=['message'])
df

,timestamp,username,message
0,2025-11-02 14:56:26,@markxushi,halo mpl
1,2025-11-02 14:56:27,@IRVAN_24,gak sesuai jadwal
2,2025-11-02 14:56:27,@ZyyyElMahir,it's onic time
3,2025-11-02 14:56:31,@Sandi-or4rd,1556
4,2025-11-02 14:56:32,@am_I02,jam 17:00 paling lambat jam 7:00 malaem haha
...,...,...,...
9987,2025-11-02 16:52:36,@ahmadrifai3360,jam berapa main?
9992,2025-11-02 16:52:39,@mariasama3870,anjay rame banget
9993,2025-11-02 16:52:39,@taaclover,bismillahirrahmanirrahim ya allah bisa yok bisa
9995,2025-11-02 16:52:40,@Zynko20,er er qi main jam berapa bang?
9996,2025-11-02 16:52:40,@Heavy_poison,barikah787

In [91]:
def cleaning(text):
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'@[A-Za-z0-9_]+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'(.)\1+', r'\1\1', text)
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['message_clean'] = df['message'].astype(str).str.lower()
df['message_clean'] = df['message_clean'].apply(cleaning)
df = df.drop(columns=['message'])
df

,timestamp,username,message_clean
0,2025-11-02 14:56:26,@markxushi,halo mpl
1,2025-11-02 14:56:27,@IRVAN_24,gak sesuai jadwal
2,2025-11-02 14:56:27,@ZyyyElMahir,it s onic time
3,2025-11-02 14:56:31,@Sandi-or4rd,
4,2025-11-02 14:56:32,@am_I02,jam paling lambat jam malaem haha
...,...,...,...
9987,2025-11-02 16:52:36,@ahmadrifai3360,jam berapa main
9992,2025-11-02 16:52:39,@mariasama3870,anjay rame banget
9993,2025-11-02 16:52:39,@taaclover,bismillahirrahmanirrahim ya allah bisa yok bisa
9995,2025-11-02 16:52:40,@Zynko20,er er qi main jam berapa bang
9996,2025-11-02 16:52:40,@Heavy_poison,barikah

In [92]:
df.isna().sum()

timestamp        0
username         0
message_clean    0
dtype: int64

In [93]:
norm = {
    "gg": "good game", "ggwp": "good game well played", "wp": "well played",
    "ml": "mobile legends", "mlbb": "mobile legends", "onicc": "onic",
    "gak": "tidak", "ga": "tidak", "nggak": "tidak", "gk": "tidak",
    "bgt": "banget", "wkwk": "tertawa", "wk": "tertawa", "awok": "tertawa",
    "pls": "tolong", "plis": "tolong", "ae": "alter ego",
    "utk": "untuk", "dgn": "dengan", "jg": "juga", "sy": "saya",
    "klo": "kalau", "krn": "karena", "tdk": "tidak", "sdh": "sudah"
}

In [94]:
def normalisasi(text):
    for i in norm:
        text = text.replace(i, norm[i])
    return text
df['message_clean'] = df['message_clean'].apply(lambda x: normalisasi(x))
df

,timestamp,username,message_clean
0,2025-11-02 14:56:26,@markxushi,halo mpl
1,2025-11-02 14:56:27,@IRVAN_24,tidak sesuai jadwal
2,2025-11-02 14:56:27,@ZyyyElMahir,it s onic time
3,2025-11-02 14:56:31,@Sandi-or4rd,
4,2025-11-02 14:56:32,@am_I02,jam paling lambat jam malalter egom haha
...,...,...,...
9987,2025-11-02 16:52:36,@ahmadrifai3360,jam berapa main
9992,2025-11-02 16:52:39,@mariasama3870,anjay rame banget
9993,2025-11-02 16:52:39,@taaclover,bismillahirrahmanirrahim ya allah bisa yok bisa
9995,2025-11-02 16:52:40,@Zynko20,er er qi main jam berapa bang
9996,2025-11-02 16:52:40,@Heavy_poison,barikah

In [95]:
factory = StopWordRemoverFactory()
stopwords_list = factory.get_stop_words()
kata_penting = ['tidak', 'enggak', 'bukan', 'jangan', 'tapi', 'sangat', 'kurang', 'lebih', 'belum']
stopword = [word for word in stopwords_list if word not in kata_penting]
stopword.extend(['rt', 'user', 'url', 'yg', 'dg', 'dgn', 'ny', 'd', 'kalo', 'klo'])
topwords = set(stopword)

def hapus_stopword(text):
    words = text.split()
    return ' '.join([word for word in words if word not in stopword])
df['message_clean'] = df['message_clean'].apply(hapus_stopword)
df = df.drop(columns=['username', 'timestamp'])
df.to_csv("data_bersih.csv", index=False)

In [96]:
#tokenize
tokenized = df['message_clean'].apply(lambda x:x.split())
tokenized.head()

0                                         [halo, mpl]
1                             [tidak, sesuai, jadwal]
2                                 [it, s, onic, time]
3                                                  []
4    [jam, paling, lambat, jam, malalter, egom, haha]
Name: message_clean, dtype: object

In [97]:
# stemming
def stemming(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    hasil = []
    for i in text:
        data = stemmer.stem(i)
        hasil.append(data)
    data_clean = []
    data_clean = " ".join(hasil)
    print(data_clean)
    return data_clean
tokenized = tokenized.apply(stemming)
tokenized.to_csv('hasil_stemming.csv', index=False)

halo mpl
tidak sesuai jadwal
it s onic time

jam paling lambat jam malalter egom haha
jantidakn bahas tidak
rolling on the floor laughing rolling on the floor laughing rolling on the floor laughing
orang jadwal nya aja

ntidakret
lah jam
mpl id scamming
kobtoll
rrq malter egon habis subuh
woi lama
kasi evos kalah ama king alter ego
tidur aja dulu gess jam
its onic time
its onic time nauseated face nauseated face nauseated face nauseated face
mpl wacana cuki
woi duit bukan
lah kata
onic
hallo
pembohonk publik

mpl ntidakntuk
udh jam bal
jam malam kont
akun uda mulai live
mulai wehh lama kali
kalian nungood tidakmeu apa jam kocak
noob vs noob
stress tidakush bikin jadwal jam sgini akhir nya malter egonn nya malemm mahh
undur kocak

nya jam
guys
palintidakn antar jam
udah ribu nungood tidakmeuin loh loudly crying face loudly crying face
al in onic
woi manawoi
onic
lah gw kira telat
kocak udah hampir jam
kapan we
admin tll
jam pas kek
udh ki
sih kek kemarin
mana final oii
jam brp
hadehh
php in sma atmin mpl jirr cat with tears of joy cat with tears of joy
scam sidai ramai
kapan mulai nya woy
mpl kocak
dah lewat jam nih
c
woii tepat waktu napa
bilang cemilan ph pindah aja lu ph
udh yappingnya
papua udh jam
ez server vs ez server
nahh
akhir
akhir tertawa
batu mulai
udah
atmin ntidakpin sih
ntidakret
gelo
go onic time hedgehog red heart
sabar
geloo cendol
nah

let s go
alter egoalter ego
iklan nya lamaa
yeszz
malter egon jm
nah tuh bru

ntidakret woi
onic kroco
lu manado jakarta jutidak bom mulai nih mpl
sapa tadi bilang jam
lama banget
lets goo alter egoe
woilah nungood tidakmeu mnit
bener jam berapa tot
alter ego mbapuk
hahah kene scammed baru on lagu
baru yanyi yanyi sampe setentidakh jam
liat postintidakn baru mpl jam mulai
alter ego
bismillahh onic
kapan rrq main
hahaha
ntidakret wee
alter ego
woi cendy pulang
mulai tidakpenting dlu ini jam baru match nya
telat setentidakh jam
bismillah onic
selamat menungood tidakmeu mnt lagi loudly crying face
caster nya siapa sekarang
yanyi dulu menit tertawaakak
goo onic
gw kira gw pertama face with tears of joy face with tears of joy
onic time
admin hbs makan ayam geprek
tidakss
tertawaktertawa musuh fans alter egoron
onic
alter ego filling gw
awas alter ego jadi jadi rolling on the floor laughing face with tears of joy
lets go alter ego be the champion
onic alter ego
gogogo
yos
cendyy
tidaks alter ego yakin menang
alter ego ukir sejarah
ngopi dlu nungood tidakmeu
ayoo onic goo onic
goo onic
jir bang cendy
semantidakt alter ego salam malaysia
bismillah skylar petidakng piala mpl
kekny jm mulai matchny
let s goo
final seru sama kuat tp lebih kuat bakal jadi juara
tadi minutes
bissmilaah onci goo
kata mulai udh mau jam blum apa apa
goo alter ego
main jam kek
rrq main jam brpa
alter ego letsgoo
alter ego go go go
min clip youtube orang grand final uda main
rrq goa
goo onic
alter ego pulang aja
semantidakt landak lucu red heart
inti bohong publik
alter ego go go go
onic menang
what it s time
goo sonic
bismillah semotidak onic pleading face pleading face
serah menang tim apa karna duaduanya tim favorit ku
bismillah alter ego
awas alter ego jadi jadi winking face
its onic time
its onic timee
ndasmu go go go
beras
lahh cendol tertawatertawa
nino maaf koh face blue smiling
main nyaa jm
lah fun match
nungood tidakmeu jam
semantidakt onic
semotidak onic menang salam blantidako
lama menit
onic juaraa clip
squinting face with tongue backhand index pointing up
letsgoo alter ego
onic lest go
magrib mah mulai guys
tenang onic juara
apa kok cendy
yok onic bisaa
lama
banyak sarkas player benar iri player malter egon tidakme terus dapet tidakji
harap onic juara sih
dukung onic mana suara
bismillahirrahmanirrahim semotidak onic menang
jam mulai
semotidak alter ego juara biar juara baru warna baru jantidakn team aja juara

tidaksabar liat skylar juara onic
onic
mulai jam berapa woii
akhir lipe
letsgoo alter ego
lets goo kink alter ego vs skyking onic
vii

onic
yok alter ego yok
sepi tidak king rrq
alter ego mau pulang sendiri apa pulangin onic
alter ego lokal pride
alter ego
jir lama banget jam
lama
kapan mulai woi
kalau lihat main juara baru season
onic
alter ego go go go
mnt bun ngobrol
alter ego alter ego alter ego alter egoe
alter ego juara
badut
kalimat lucu alter ego ukir sejarah
mnt
dah selesai yaa
alter ego juara yokk
wtf cendy
face red droopy eyes
lama
onic my heart
scam
mpl id dentidakn tetidaks tentang setidakla bentuk judi dukung kompetisi adil integritas bangun komunitas hormat nilai nilai sportivitas dunia esports
woi
jam brp grand final mulai
langsung aja kasih piala mpl nya onic piala m tlph face blue smiling face blue smiling
siap siap king alter ego antidakat piala
jam lama kok sdah rame aja
setidaknteng bilang badut face with tears of joy face with tears of joy
alter ego go go g
let s go alter ego
tandain gw onic juara gw botak pile of poo
apaa dulu
mulai nya kapan dah
go go onic
alter ego ukir sejarah baru
rrq juara nih
udh sonic tidak usa nonton alter ego bakal juara
grandfinal mulai ntar subuh kocak
evos evos divine tidakada apa
m kapan
alter ego juara catat
dah tau siapa juara nya
juta ayok gw alter ego
lagu shinbi jier
onic alter ego
onic lh jls
onic juara
tidaks onic
lahh kok bang crispy
alter ego juara fix
semotidak kejut buat alter ego
ketika banyak ntidaku sonic face with tears of joy
onic juara catat
fans karbitan

rrq kapan main
skip cendyy
alter ego onic tidak usah bawa tim
jta onic
alter ego cik juara sonic out aja
jm brp mulai ntidakb match satu
sonic lari nek
ssmotidak onic lose
rrq juara goa rolling on the floor laughing rolling on the floor laughing rolling on the floor laughing
onic menangood tidakme
alter ego juara
onic timee
dah main ngood tidakmea sih
nungood tidakmeu jam baru mulai
kasihh alter ego aja piala nyaa
jam berapaa main
onic juara tandain guee red heart
xepher jenius njir
sonic lahir nek
atas onic alter ego rolling on the floor laughing
bismillah onic
jam brp
onic jt sini
onic
sepi tidak sana
jam brpa malter egon nya
go alter ego go alter ego go
alter ego juara rana alter ego on fire and lama nanti sedantidakan onic mas posisi selesa
nya alter ego juara
delwyn dellost nih guyss

onic go to goa lah alter ego juara
bismillahirrahmanirrahim semotidak onic juara
p
kasih baik aja dua team
petidakng ererq jt all in
rrq tidak undang kasihan huahahahhaa
alter ego
jam baru mulai
nt onic
rrq kapan
alter ego onic
alter egoe juta
onic lose boss
fans onic jejer blng anic time
ntidakpain kesi
catat tidakiss alter ego juara
lama kali cok
jam berapa sih mulai
rrq main nya jam brp
onic skylar
fokus diri masing aja
yapping

hidupp rrq
alter ego juara ni
ngetik alter ego win sonic jmbd
savero main
atas onic rrq
ceban
alter egoe lah onic udah gbkln juara kemaren udah juara tidak muntidakin juara lagi
alter ego gogogogo
rrq jam brp main
sonic kumpul squinting face with tongue backhand index pointing up
alter ego champion
jam mulai
onik
ntidakak baca loudly crying face
opet
jam brp kak
main jam brapa
rrq dah juara m woyy
alter ego onic
hujan redah nya cuyy
onic
jam mulai
alter ego
final rrq vs tlid rolling on the floor laughing
counter tlph cuman onic tidakys face with hand over mouth
jt onic
t
onic alter ego
onic posisi udah selesa cuma belum piala m series piala mpl udah banyak kalau onic kalah sini no effect apa apa alter ego on fire jadi aura nyaa kuat
rrq main jam berapa yak
mat seru ni
rrq dah juara m woy
tandain mvp nya yazukee
misi balas dendam alter ego ni face blue smiling
counter tlph cuman onic tidakys face with hand over mouth
ayok onic it s onic time
onic menang
mnit
match jam berapa
alter ego ulang apa tlid laku
fun match harus undang badut rrq
semotidak alter ego menag yaallah
inioc
cendy ntidakpain
bismillah onic juara
jam main udah live hahaha
kok bawa bawa rrq dah
apa onic
yeahh mnit lgi
main jm berapa
ayo landak kuning hedgehog
go alter egoe
fans fanatik rrq mana nih tertawaw face purple crying
ayo onic ayo alter ego kasih lawan asik
bismillah semotidak onic menang palms up together
semantidakt alter ego
onic onic
king alter ego siap bantai

lah bang cendol tertawa
solat dulu ges
sejarah mpl s is bsck
skylar kairi dikantongin yazukee
rrq goa ajar tembak toy toy toy
go kairi red heart hedgehog
bismillah alter ego juaraa
mana
main jam berapa
semotidak onic menang allah smiling face with halo folded hands
mama aku m
mulai terlalu sore
go alter egoe
onic m bismillah
ko blm mulai
onic back to back champions
lembar merah onic
albaniakbar caper banget kurang perhati ortu
semotidak hari keberuntuntidakn buat tim suka ku menang onic
onic onic onic
bismillah semotidak alter ego juara loudly crying face
rrq ukir sejarah
ayo alter ego tolongs kalian bisaa
lama njit
mulai jam ges
onic onic
sekali onic tetap onic
jam brpa main
lamaa
mamah aku m
jam
baru baca langsung hilang face with tears of joy
onic sama madrid jarang kalah final
alter ego bismillah
ez onic inimah
bismillah onic menang
sorry end thenk you it s my stail
juta alter ego
ayo ajak lembar merah gua alter ego nih
mulai jam ges
mulai jam berapa
jt yuk aku pengood tidakmeang alter ego
baru mulai
semotidak onic kalah
mana notif munn
semua bilang terima kasih sutsujin alter ego m atas statement bilang alter ego tidak tidakmeplay bukti alter ego punya tidakmeplay lolos m
juta onic
ayo gua onic
jam lima baru mulai
juta alter ego sini gua tampung cat orange whistling
juta onic
fg dr
gd g df
dfg
fd g
fd
gfd
jt onic berani ngood tidakmea
hi
menang alter ego
person turqouise waving
kapan mulai si
kontak kontak
ayo semantidakt onic
m
onic main jam brp bng
sorry koh gw ngecewain lu
jt aku petidakng budhe
shushing face
mas lama co
jt gw onis sini
jam berapa sih mulai
ayo jantidakn hilantidakan
jam berapaa
juta alter ego
langsung aja kasih piala onic
tidak judi kalau kalian taruh pake uang sama aja dentidakn berjudai
tolongs remehin alter ego biar menang
yo gua tampung nih mau berapa juta

jt berani gw onic
bismillah alter ego menang
bismillah onic antidakat piala palms up together red heart
sini evos jt
text green tidakme over
jt gw onic sini
alter ego
sini evos jt
sepi
gua alter ego nih
admin sibuk ngespam tertawatertawak
dukung onic mana suara elbowcough
onic dong
lama jirr
napa si cendol tawak
onic gw
alter ego tidakss
mulai nya
alter ego vs onic jam brpa
sini rrq m
rrq jayaa
gua onic mna evoss jt sini
goo goo onic
nicc
udah jam nihh woyy
kira tlph doang apa jago tertawatertawa srg jutidak jago woyy
semua bilang sutsujin buat alter ego m
jt alter ego
onic jta
sih malter egonnya
kindom goa sinyal buat nonton serius nanya

goo alter egoe
pov papan atas bukan
jt gw alter ego sini
onic
skyleerr
onic go go go
grand final belum final
petidakng evos sini gua alter ego jt
juta onic
mulai jam berapa
mau jt gw petidakng alter ego
alter ego tidak da tidakmeplay
bang gue live tapi sepi
laah ntidakpain fun match
onic
landak landak ntidakrep juara alter ego nih gua
onic go go
gua onic bakal juara alter ego cupu
alter egoe
cendoll
kasih langsung piala onik
juta onic
alter ego bego bego bego
jam brpa mulai nya
aku onic jta
bawa trophy gh alter ego no
jt onic
langsung aja min
biar senam jantung
alter ego menangood tidakme
alter ego
hand pink waving
onic alter ego sanz mvp
gue pilih menang aja rolling on the floor laughing
lets goo onic
all in jt alter ego
alter ego pulang aja juara onic
lama yak
geloo ketuaa
kena kencing lg
persib
alter ego goo
t onic
alter ego
yokk nic
milliar rrq
alter egoe
paling ntar mulai jam kek kemaren
onic
akwoakwoka
tempek
bravo nino
jt alter ego
siapa aja juara gw happy
w ken liat alter ego menang tp ken liat skylar bukti baru main juara
onic alter ego
onic
jam main tungood tidakmeuin aja
letss go onic
onic
panic
alter ego yok champion
jt all in alter ego
hujat alter ego fansnya kongdom
sanz mvp
its rrq time
jadi judi
gw mau liat nino nang antidakat piala mpl
onic
rebut piala
onic
alter ego
siapa santidaka
piala onic
jt all in onic

alter ego
woo
menang ditungood tidakmeu king rrq m orange heart
onic alter ego
siapa juara semantidakt terus heart suit
lama habis magrib mai
angood tidakmeota dri mpl tidak byr uang taruh gua anjuga
alter ego nii broo
nino nang antidakat piala mpl
let s go final rrq cat orange whistling
alter ego
kali
walaupun onic kuat tapi gw tetap sokong alter egoe
all in alter ego
mpl nyari beras
alter ego yok
onic juara
bocil fomo onic diem aja lah
let s goo alter egoo
yng menang rrq
udah onic kasih aja piala alter ego kasihan nino winking face with tongue winking face with tongue winking face with tongue
lest goo alter ego
alter ego ayo
o n i c
gw metidakng alter ego sini
onic goo
gw kingdom alter ego kalah
rrq m lewat jalur panarukan
alter ego broo
ayaloh alter ego
mpl sentidakja kek grandfinal awal bulan
goonic
onic bismillah
goo onic
alter ego kalahh tertawatertawawakkw
onic timee broo
statement sutsujin mimpi bilang alter ego tidak tidakmeplay liat tuh alter ego m tertawatertawatertawa aduh ujin ujin mending mpl my aja ujin tidak usah sama tim badut m series
jt metidakng onik sini

alter ego alter ego alter ego
alter ego win
go nic
tlph bagi telor ama rrq tlph mah team ez
gogogo alter ego
udah tebak juara onic
jt gua petidakng rrq face fuchsia tongue out
lma
alter ego juaraa sih
motidak rrq juara
liat onic kalah ntar
onic timee
go alter egoe dove
ketika banyak ntidakju jadi sonic face exhaling
lama cokk
gue kindom gue dukung alter ego
alter ego yo bikin ko delwyn neng
indo indo
mana tadi petidakng alter ego gw tampung
alter ego menangood tidakme ezz
jam brp mulai
ayo alter ego
waktu alter ego bukan onic face blue smiling
siapa juara gua tetep respect buat alter ego sama onic team selalu respect sama lawan nya thumbs up
tid is onic time
nn
waktu alter ego bukan onic face
alter ego championss
rrq juara m
id ikut
lah cendy
alter ego menang hebat sii
semotidak alter ego juara
alter ego
final onic vs evos jam brp
bismillahh goo onic
ayo onic
mulai jam wib adik
alter ego juara sih
santidak cooll
yalter ego gua selasa goreng telor blm mulai
alter ego gogogo
alter ego it s time
prediksi
lets goo alter ego
fans alter ego buru udah kalah jutidak
rrq goa cuak
semua hujat aja sutsujin bilang alter ego tidak tidakmeplay liat alter ego m omontidakn sutsujin omong kosong
saat juara alter ego
onic alter ego
atas langit onic
alter egoe menangood tidakme
onik lah juara nya
alter ego gope dm gua
blok admin judi tertawa
final onic vs evos jam berapa
goo alter ego
let s gooph
alter ego lu tong
bismmilah onic
waktu onic
pasti bisaa onic
el family is back
semotidak alter ego menang
prediksi
waktu onic bukan saluting face
saat onic bukan alter ego
bismillah alter ego juara
let s goo kairuu
rrq goa tidak keluar keluar
tl
alter ego apa lah alter egoe
all in alter ego
jt petidakng alter ego
alter ego
prediksi menang siapa ges
onic back to back
onic handshake alter ego
semotidak alter ego menang juara mpl id s
butuh juara baruu
kira jam brp matchnya
kirain evos vs onic
alter ego sih
p e p e q q o n t o l k o n g o m
alter ego juara gilo ng skylar
rrq main jam berapa hand orange covering eyes
alter ego mpl king onic m bismillah
walaupun gwe sonic tp gwe pgn liat alter ego menanh
sholat dulu guys
rrq lu mending main pou aja
kasih aja alter ego onic biar mpl indo tidakbosen lu terus juara
rrq main jam brp
onic id juara
this is alter ego time
bo lama banget atuh
let s goo onic vs alter ego siapa menang baik s next bawa pulang piala m
let s go king arfy
alter ego
waktu alter ego bren bukan onic trophy yellow smiling
yok onic
lets go alter ego
info rrq vs persib jam berapa
alter ego dipulangin sama onic winking face with tongue
jt sini gua onik yok
dm
sini petidakng alter ego jt tadi
ayo onic kasih piala nya alter ego aja
alter ego king
goo onic
come on alter ego
onic dapat tiket m let s go onic ku
aku
semotidak onic menang tapi kasih scor alter ego
alter ego champion
rrq main jam berapa elbowcough
ayo alter ego
merah lembar petidakng onic
siapa menang gua senengood tidakme
rrq main
seterah siapa menang
alter egoe rb
langsung aja kasi piala alter ego biar mpl tidak bosan tertawa masa onic ters juara tertawatertawa
alther ego go go go
tolongs alter egoe
semua bilang sutsujin jantidakn rrq mending srg rrq badut m series tambah tidaktidakl playoff
king alter ego
onic handshake alter ego
gua dukung menang
face purple crying
alter ego hoki udh habis tub yakin gw
alter ego go
jam
onic menang
votenya mana min woyy
alter ego bismillah win mpl pertama kali nya
onic jt tidakss
semantidakt jumengood tidakme siap mukbang king krab
exsper farming aura

letsgo
siapa menang gua neng
onic juar
nino wujud impi
indopride tidakess
yok alter ego alter ego jaya juara antidakat piala
alter ego gogogo
admin tidak peka nih
lamaa
nya tim keren humble
siape kite
ngood tidakmeak rrq dukung alter ego juwara
alter ego edwi face blue smiling n striming
mulai

jt onic
petidakng alter ego jt tadi mana woii dm gua
bjir anomali mulu
nino goat
both lose both nob
goo todak

indo indo rolling on the floor laughing rolling on the floor laughing rolling on the floor laughing
todak
bro nanya rrq juara berapa
tolongs jantidakn bangood tidakmeain alter ego kalau fans alter ego wajib under kkan alter ego
ayoo alter ego juara ken banget liat nino juaraa smiling face with halo smiling face with halo
alter ego ukir sejarah part
xepsre
votenya mana min oyy
siapa fun match coba lah undang mantn pro player old jutidak seru nya
lontee
sonicalterchamps
onic menang karna legend mm hayper sekailar kairi
mana metidakng alter ego juta sih dm gua
david gengood tidakmeek
lama banget
gue alter ego juta
ayo final oi
alther ego go go
high domino
anomali
sutsujin statement nonsense
alter ego go go go go go
nino goat alter ego king
oi jugan provokator jir
dejavu
mulai jam brp ni final
menuu m
rrq main jam berapa
alter ego mending suren aja
knp cendy anj
ntidakpain cendi jir
spam vote guys
tidakss
u
alter ego wajib juara sih
st place medal trophy
serius tidak vote nya ni min
dm gua petidakng alter ego jt
ayo aktif pasif alter ego
tidak tim tidak viewers nya hahaa indo indo rolling on the floor laughing rolling on the floor laughing rolling on the floor laughing
rrq gogo
biar admin kerja
alterchamp
final jam broo
mana woii
goo alter ego
onic juara balas kalah evos
vote
tidakmau onic dah banyak piala mpl nanati onic m aja
alterchamp mana suara
alter ego juara
rrq go
cendy drak sistem
go rrq
vote min
chip chip domino
alter ego onic
m
gf nta rrq lawan mana gess beaming face with smiling eyes
alterchamp goo
rrq raja setidakla raja goa
m tidaks
tlph bagi telor ama rrq tlph mah team ez onic mah tim apa
woii
admin ntidakntuk
rrq kapan malter egon
indo indo indo rolling on the floor laughing rolling on the floor laughing rolling on the floor laughing
trophy yellow smiling onic
hahahahah egood tidakmepos kapan malter egon gess
sematidakt
onic trophy yellow smiling
sini jt gw petidakng onic face blue smiling
go rrq go to the bank tidakme

alter ego go go go go go go
votenya mana min
ayo onic
rrq badut
kingdom ayam
nyo rekber tidak
onic kalah
gue alter ego juta serius
kiukiu
jantidakn cari tidak ads
bandar qq domino
grand final nya rrq vs mana gess face with hand over mouth
yt yt yt yt
alter ego is next the champion
index pointing up clown face
lama astatidaka
butuh vote
let s go alther ego
evos kapan main
kiumiu
rrq turu sleepy face sleepy face
waktu uang
hm
eek
remehin alter ego biar juara moa
juta alter ego
onic menang lah
alter ego semantidaktt
juta alter ego
kurumu
berani taruh juta onic vs alter ego
my kairi loudly crying face loudly crying face
kingdom dukung alter ego karna nino jutidak dukung alter ego karna benci onic face with tears of joy fakta
lest go alter ego
this is onic timee
tidaks alter ego jt
onic jatuh dr langit
udh onic menang
match mentidakndung beras
gelo cendy
rrq
rrq juara mulu bosen jadi
onic vs alter ego juta sini wa
alter ego gokgokgokgokgok
lama banget mulai
alter ego tim apa rrq punya long jago kagura speaking head
jam berapa mulai nya
dong alter ego juara
tidaksken
card red penalty
domino
draf bagus hero pool byk
bismillah onic juara trophy